name: Convert to Upper Case

inputs:
  test_string:
    type: string
    required: true

runs: 
  steps:
   - name: Convert
     run: |
            if [[ ${{github.event.inputs.test_string}} =~ ^[a-zA-Z]+$ ]];then
              echo ${{github.event.inputs.test_string}} | tr '[:lower:]' '[:upper:]'
            else
              echo "There is a neumeric value"
            fi
     shell: bash